### ISSUE TITLE
tiny idea: Commemorative inspector gadger

### ISSUE THREAD

**Issue by piratabrasileiro1** [SiIvaGunner-Database/SiIvaGunner-Database#59]
Could have a different inspector  gadget image for each special day

**Comment by AAAAAAidan** [comment]
Hello. I know the anniversary of Minecraft with Gadget is May 11th, but are there other notable days coming up as well?

**Comment by piratabrasileiro1** [comment]
well, I was thinking about having real special days  like Christmas, but recent channel events I haven't seen any

**Comment by AAAAAAidan** [comment]
I put together a couple small changes for the 7th anniversary of "Minecraft with Gadget" on May 11th. The changes probably won't be permanent, but it was fun to do, so I'll think about making similar changes for other events in the future. Thanks for the idea!

**Comment by piratabrasileiro1** [comment]
You're welcome
